#--------------------------------------------------------------------------------
# cONTsensus Configuration File
#--------------------------------------------------------------------------------
tmpdir: '/tmp'
project: 'barcode04'

# Raw Fastq file: (initial input file)
#----------------------------------------
raw_fastq: 'Input_Files/Microbiome_barcode04.fastq'

# Quality filter Configuration (# iterations)
#L_filt: refers to the minimum lenght for a read to pass filters
#---------------------------------------------------------------
quality_filter: [6,7,8]
L_filt: '800'

#Program Files Location
#----------------------------------------
# This includes the location of running programs
# Also contains the number of available threads to run when the program support it
#--------------------------------------------------------------------------------
n_threads: '150'
porechop_runner: 'bin/Porechop/porechop-runner.py'
guppy_barcoder: 'bin/ont-guppy-cpu/bin/guppy_barcoder'
guppy_aligner: 'bin/ont-guppy-cpu/bin/guppy_aligner'
ProwlerTrimmer: 'bin/ProwlerTrimmer/TrimmerLarge.py'
Filtlong: 'bin/Filtlong/bin/filtlong'
seqtk: 'bin/seqtk/seqtk'
blastn: 'bin/ncbi-blast-2.13.0+/bin/blastn'
16S_ppm: 'bin/16S_ppm/16S_ppm_output.py'

#Databases Location
#----------------------------------------
# This includes the location of all available databases
db_16S_ribosomal_RNA: 'databases/16S_ribosomal_RNA/16S_ribosomal_RNA'
db_ggc: 'databases/GGC_db/Green_Gene_Consensus'
#BLAST parameters
#----------------------------------------------
# This section set parameters for BLAST commnad
max_target_seqs: '10'
evalue: '0.00001'

#This parameters can be changed in the 16S_ppm file
#align_coverage_cutoff: 0
#align_perc_id_cutoff: 0
