#--------------------------------------------------------------------------------
# cONTsensus Configuration File
#--------------------------------------------------------------------------------
tmpdir: '/tmp'
project: 'barcode04'

# Raw Fastq file: (initial input file)
#----------------------------------------
raw_fastq: 'Input_Files/Microbiome_barcode04.fastq'

# Quality filter Configuration (# iterations)
#L_filt: refers to the minimum lenght for a read to pass filters
#---------------------------------------------------------------
quality_filter: [6,7,8]
L_filt: '800'

#Program Files Location
#----------------------------------------
# This includes the location of running programs
# Also contains the number of available threads to run when the program support it
#--------------------------------------------------------------------------------
n_threads: '150'
porechop_runner: 'bin/Porechop/porechop-runner.py'
guppy_barcoder: 'bin/ont-guppy-cpu/bin/guppy_barcoder'
ProwlerTrimmer: 'bin/ProwlerTrimmer/TrimmerLarge.py'
Filtlong: 'bin/Filtlong/bin/filtlong'
seqtk: 'bin/seqtk/seqtk'
blastn: 'bin/ncbi-blast-2.13.0+/bin/blastn'

#Databases Location
#----------------------------------------
# This includes the location of all available databases
db_16S_ribosomal_RNA: 'databases/16S_ribosomal_RNA/16S_ribosomal_RNA'

#BLAST parameters
#----------------------------------------------
# This section set parameters for BLAST commnad
max_target_seqs: '10'
evalue: '0.00001' 



##list_of_scripts=[fromfasta_16Spipe.py, fromfastQ_16Spipe.py]
#script_fromfasta=fromfasta_16Spipe.py
#script_fromfastQ=fromfastQ_16Spipe.py
#num_threads=140
#porechop_runner=bin/Porechop/porechop-runner.py
#porechop=1
#Nanofilt_runner=bin/miniconda3/bin/NanoFilt
#Nanofilt=1
#Filtlong_runner=bin/Filtlong-master/filtlong
#Q_filt=7
#L_filt=800
#max_num_fasta=20000
#min_num_fasta=1
#db=NCBI_16S_db/PRJNA33175_Bacterial_16S.fasta
#blastn="bin/ncbi-blast-2.9.0+/bin/blastn"
#max_t=5
#evalue=0.00001
#align_coverage_cutoff=0
#align_perc_id_cutoff=0
